version: '2'
services:
  bridge-backend:
    image: harbor.nekotal.tech/dev-middleware/bridge-backend-service:$TAG
    stdin_open: true
    network_mode: host
    volumes:
      - /root/config.json:/app/config.json
    tty: true
    environment:
      - FILE_PATH=.
      - FILE_NAME=config.json
    labels:
      io.rancher.scheduler.affinity:host_label: io.rancher.host.os=linux
      io.rancher.container.pull_image: always
      io.lachain.service: bridge-backend
    depends_on:
      - "db"
  db:
    image: postgres
    restart: always
    network_mode: host
    stdin_open: true
    command: -h 127.0.0.1
    volumes:
    - /root/pg_db:/var/lib/postgresql/
    labels:
      io.rancher.scheduler.affinity:host_label: io.rancher.host.os=linux
      io.rancher.container.pull_image: always
      io.lachain.service: bridge-backend
    environment:
      POSTGRES_PASSWORD: postgres
